services:
    parcelorder_emailsender.handler:
        class: AppBundle\Handler\ParcelOrderSendEmailHandler
        arguments: [ '@twig','@mailer' ]
    user_emailsender.handler:
        class: AppBundle\Handler\PasswordRessetingEmailHandler
        arguments: [ '@twig','@mailer' ]
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

